responses = [
    "Calculating bond...",
    "Calculating if I will give you the last slice of pizza.",
    "Finding matching interests",
    "Talking to your parents",
    "Consulting with my best friend",
    "Analyzing your vibes...",
    "Browsing your meme history...",
    "Checking star alignment...",
    "Scrolling through your past mistakes...",
    "Asking my cat for advice...",
    "Looking for signs of emotional damage...",
    "Sorting your priorities...",
    "Debating with my inner self...",
    "Syncing brainwaves...",
    "Loading sarcasm levels...",
    "Tuning into your playlist...",
    "Replaying your childhood trauma...",
    "Whispering to the universe...",
    "Checking Wi-Fi stability...",
    "Googling your name in incognito...",
    "Rewinding awkward conversations...",
    "Searching for your chill...",
    "Surveying your snack drawer...",
    "Summoning emotional support AI...",
    "Wading through your search history...",
    "Polling imaginary friends...",
    "Cross-referencing with astrology data...",
    "Peeking into your dreams...",
    "Scrolling through potential regrets...",
    "Verifying with your past self..."
]
